### ISSUE TITLE
Error on Query

### ISSUE THREAD

**Issue by glsmith777** [simplextech/udi-poly-inventory#2]
Greetings - I installed the isy inventory.

When the Query button is selected, the following error is displayed in the log:

2021-01-03 01:43:21,113 Controller polyinterface      ERROR    polyinterface:_parseInput: _parseInput: failed controller.runCmd(DISCOVER) can only concatenate str (not "bytes") to str
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 842, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/home/pi/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 745, in runCmd
    fun(self, command)
  File "./inventory-poly.py", line 76, in discover
    node_resp = self.get_request(nodes_url)
  File "./inventory-poly.py", line 53, in get_request
    LOGGER.error("ISY-Inventory.get_request:  " + r.content)
TypeError: can only concatenate str (not "bytes") to str

**Comment by simplextech** [comment]
Error message Resolved in last update 0.1.2.  Update NodeServer and restart.  Ensure NodeServer is actually configured as the error happens when it can't reach the ISY.
