### ISSUE TITLE
Apparent crash

### ISSUE THREAD

**Issue by Bumbershoot1** [simplextech/udi-poly-inventory#3]
2021-03-04 05:34:48,732 Controller polyinterface      ERROR    polyinterface:write: Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 852, in _parseInput
    self.shortPoll()
  File "./inventory-poly.py", line 36, in shortPoll
    self.discover()
  File "./inventory-poly.py", line 77, in discover
    node_root = ET.fromstring(node_resp)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1316, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: unclosed token: line 1, column 178428

**Comment by simplextech** [comment]
Well that's new.  Is this running on Polisy and latest updates?

**Comment by Bumbershoot1** [comment]
Yes to both. I didn’t notice it for a few  days.  It started right back up.  I’ll watch it.

**Comment by simplextech** [comment]
Did the ISY reboot or something occur?  Looks almost like it failed connecting to the ISY during the daily shortPoll to update.

**Comment by Bumbershoot1** [comment]
No, the ISY didn’t reboot until I installed the latest firmware a few days later.  There might have been some network issue, I don’t know.  In any event, it’s running fine again.
